name: 'Build'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.vscode'
      - '.github/workflows/release.yml'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        arch: ['x64', 'arm64']
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # https://github.com/pnpm/pnpm/issues/4473
      # dirty hack
      - name: Install dependencies
        run: |
          pnpm i
          pnpm i -w @nekosu/maa-node-${{ matrix.os == 'windows-latest' && 'win32' || (matrix.os == 'ubuntu-latest' && 'linux' || 'darwin') }}-${{ matrix.arch }}
          rm -rf node_modules/@nekosu/maa-node-${{ matrix.os == 'windows-latest' && 'win32' || (matrix.os == 'ubuntu-latest' && 'linux' || 'darwin') }}-${{ matrix.arch == 'x64' && 'arm64' || 'x64' }}

      - name: Compile Electron app
        run: |
          npm run build
          npm run package -- --arch=${{ matrix.arch }}
          mkdir -p pkg

      - name: Package app
        run: |
          tar cjvf pkg/`ls out`.tar.gz -C ./out ./`ls out`

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: maa-node-pi-${{ matrix.os == 'windows-latest' && 'win' || (matrix.os == 'ubuntu-latest' && 'linux' || 'macos') }}-${{ matrix.arch }}
          path: 'pkg'
